### ISSUE TITLE
Problem in zero-clock-speed-error

### ISSUE THREAD

**Issue by cgay** [Gleefre/stopclock#1]
Hi, I was just taking a brief look at your stopclock code since it's still the last thing posted in the `#showcase` Lisp Discord.

https://github.com/Gleefre/stopclock/blob/main/stopclock.lisp#L49-L51 seems to have a classic problem wherein `format` is called without an explicit format string.

`(format stream (slot-value condition 'message) (clock condition))` assumes that the value returned by `(slot-value condition 'message)` is a string and that the string will contain a format directive.  The default message for the condition doesn't contain any format directives.

Always safer to use an explicit format string: `(format stream "~A (clock ~A)" (slot-value condition 'message) (clock condition))`

Cheers.

**Comment by Gleefre** [comment]
Thanks for your feedback!
Pushed the fix to the mainstream.
