### ISSUE TITLE
Why the synonyms?

### ISSUE THREAD

**Issue by Hexstream** [Gleefre/stopclock#2]
Hello,

I noticed the mysterious `start`/`run` and `stop`/`pause` synonyms.

Why not just stick with the intuitive `start` and `stop`?

**Comment by Gleefre** [comment]
I find all four names intuitive (and I also use them all depending on the context).

**Comment by Hexstream** [comment]
Ok, well at a minimum `run` should probably call `start` rather than duplicating the code, and same for `pause` calling `stop`, or vice-versa.

**Comment by Gleefre** [comment]
Will fix that, thanks!

**Comment by Gleefre** [comment]
Fixed.

**Comment by Hexstream** [comment]
Using
`run` and `stop` as "primitives" instead of
`start` and `stop` or
`run` and `pause` seems a bit weird to me, but whatever...
